### ISSUE TITLE
モバイル版の出典表示（「地理院タイル」）について

### ISSUE THREAD

**Issue by Miyama-Kirishima** [gsi-cyberjapan/gsimaps#107]
先月のアップデート後、モバイル版において「地理院タイル」との出典表示が画面右下に表示されなくなってしまっているようです（PC版では表示されます）。
御確認いただけると幸いです。

**Comment by johofukyu** [comment]
ご指摘いただき、ありがとうございます。
修正いたしました。

**Comment by Miyama-Kirishima** [comment]
修正を確認いたしました。迅速に御対応いただき、ありがとうございました。
