### ISSUE TITLE
逆ジオコーディングでmuniCdの値が返ってこなくなってしまいました

### ISSUE THREAD

**Issue by ryuichi53** [gsi-cyberjapan/gsimaps#116]
以前からapiを利用させてもらっていたのですが
https://mreversegeocoder.gsi.go.jp/reverse-geocoder/LonLatToAddress?lat=35.681382&lon=139.766084
とするとレスポンスは
{"results":{"muniCd":"13101","lv01Nm":"丸の内一丁目"}}
のようになっていたのですが

本日あたりからレスポンスのmuniCdの値が空になってしまいます。
仕様変更などがあったのでしょうか？

**Comment by johofukyu** [comment]
ご指摘いただき、ありがとうございます。
muniCdの値が正常に返却されるよう修正いたしました。
この度はご不便をおかけしました。
