### ISSUE TITLE
ベクトルタイルの404エラーをハンドリングできない

### ISSUE THREAD

**Issue by frogcat** [gsi-cyberjapan/gsimaps#57]
XMLHttpRequest でベクトルタイルを扱っています。

タイルが存在する場合にはレスポンスに Access-Control-Allow-Origin ヘッダが付与されているので、ドメインをまたぐリクエストであっても問題なくさばけています。
http://cyberjapandata.gsi.go.jp/xyz/experimental_anno/15/29108/12907.geojson

他方、タイルが存在しない場合には 404 エラーが返ってくるのですが、この場合 Access-Control-Allow-Origin ヘッダが付与されていません。受信側では javascript のコンテクストに伝達される以前に制約が掛けられてしまうのでアプリケーションでのエラーハンドリングができない状況です。
http://cyberjapandata.gsi.go.jp/xyz/experimental_anno/15/29106/12907.geojson

エラータイル表示をしたい場合や、すべてのタイルリクエストを受信してから処理実行、のような場合にちょっと困りそうです。なお、「実験」のための優先度の低い要望とお考えください。

**Comment by johofukyu** [comment]
ご連絡ありがとうございます。
404エラーの場合にもヘッダが付与されるように設定してみました。
ご確認いただけますと幸いです。

**Comment by frogcat** [comment]
確認しました。
404エラーの場合でも XMLHttpRequest でエラーハンドリングができるようになりました。
ご対応ありがとうございます。

参考） 注記タイルを例に、地図上に Status Code と応答時間を表示するデモ
https://github.com/frogcat/gsi-vector-ping
