### ISSUE TITLE
標高APIにおける"過度の負担を与えると判断するアクセス"の目安を知りたい

### ISSUE THREAD

**Issue by tsunoria** [gsi-cyberjapan/gsimaps#72]
標高APIを利用しています。

APIの利用のために、 http://maps.gsi.go.jp/development/api.html にある

> 地理院標高APIを提供するサーバに過度の負担を与えないでください。過度の負担を与えると判断したアクセスについて、国土地理院は予告なく遮断を行う場合があります。

"過度の負担を与える"アクセスの目安を知りたいです。

他の事例として、Google Elevation API https://developers.google.com/maps/documentation/elevation/intro ではfreeの範囲で、以下のlimitが設けられています。
- 2500 requests per 24 hour period.
- 512 locations per request.
- 5 requests per second.

1requestで512地点のデータが取得可能なので、1日あたり最大1280000（2500x512）地点の座標が取得可能ということになります。

現在は1 request/sec 程度で利用していますが、もし問題があれば修正したいと思います。
以上よろしくおねがいします。

**Comment by johofukyu** [comment]
お問い合わせいただきありがとうございます。

以下の回答をご参照下さい。
https://github.com/gsi-cyberjapan/gsimaps/issues/31
