### ISSUE TITLE
オフライン環境での利用

### ISSUE THREAD

**Issue by doritosist** [gsi-cyberjapan/gsimaps#75]
インターネットアクセス不可の環境内で、独自に地図配信サーバを立てて白地図タイルを利用したいのですが、利用規約上問題ないでしょうか？
また、問題ない場合、一括でダウンロードする方法はありますか？

**Comment by johofukyu** [comment]
ありがとうございます。
下記URLの回答の「２・基本測量成果以外の地理院タイルを利用される場合」に
相当しますのでご参照ください。
https://github.com/gsi-cyberjapan/gsimaps/issues/22

また、タイルのダウンロードについては、ご参考までではありますが、以下のようなものもございます。
地理院タイル目録ベースのダウンローダ
https://github.com/gsi-cyberjapan/qdltc

よろしくお願いいたします。
