### ISSUE TITLE
地図がDLできません

### ISSUE THREAD

**Issue by day1987tona** [gsi-cyberjapan/gsimaps#77]
Rubyを使いURL：http://cyberjapandata.gsi.go.jp/xyz/english/{z}/{x}/{y}.pngしようとしています。
そうすると、「404 not found」のエラーが出てRubyが使えません。
何の設定ファイルを直せは使えるようになるかお教え頂けないでしょうか？
qdltc.rbの99行目は  url = "http://cyberjapandata.gsi.go.jp/xyz/english/#{path}"としています。

社内からインターネットへの接続環境は下記になります。
　Ruby がインストールされているPC⇒Proxyサーバ⇒FW(ファイヤーウォール)⇒インターネット

**Comment by hfu** [comment]
english のタイルセットのダウンロードを試行いただいているとのこと、ありがとうございます。

この場合の流れは、次の通りとなります。

(1) english の地理院タイル目録のダウンロード
　http://cyberjapandata.gsi.go.jp/xyz/engish/mokuroku.csv.gz
(2) 上記ファイルを置かれたフォルダ（qdltc.rb の標準版ではフォルダ名 english で）で ruby qdltc.rb 

これで、ダウンロードが始まる流れとなります。

404 not found エラーが出るパターンとしては、mokuroku.csv.gz と THEME (今回の場合は english) のズレ、それからネットワーク環境の問題が考えられると思います。前者については、mokuroku.csv.gz の取得もとが上記のとおりになっているか、ご確認ください。後者については、ruby 処理系がお使いのインターネット環境のproxy設定等を反映できているか、といった確認が必要になるかもしれません。

※いただいた issue は、qdltc.rb の課題ですので、qdltc.rb のレポジトリからも参照させていただきます。

**Comment by day1987tona** [comment]
ご回答有難うございます。
english目録はhttp://cyberjapandata.gsi.go.jp/xyz/english/mokuroku.csv.gzからDLし、任意のフォルダに置き、qdltc.rdはオリジナルのままで同フォルダに置いてruby qdltc.rb実行しました。
そうすると添付のメッセージが表示されます。
対応をご教示頂けますでしょうか。

![snapcrab_noname_2016-1-28_16-2-32_no-00](https://cloud.githubusercontent.com/assets/16694747/12637526/5fd536ea-c5d9-11e5-92aa-2563e4f2877c.jpg)

**Comment by day1987tona** [comment]
Rubyのシステムフォルダにenglishフォルダを作成し、そこに目録及びqdltcを格納する事でDLが成功しました。
別の質問となりますが、例えば標準地図のうち、地球地図(std-6)だけをDLする事は可能でしょうか？
その場合、目録DLのURLはどのようになりますでしょうか？ご教示頂ければ幸いです。
どうぞ宜しくお願い致します。

**Comment by hfu** [comment]
https://github.com/gsi-cyberjapan/qdltc/blob/gh-pages/qdltc.rb#L100 で変数 zxy にタイル番号が {z}/{x}/{y} の形（例：2/3/1）で入ります。std-6（http://maps.gsi.go.jp/development/ichiran.html#std-6 ）はズームレベル2または3または4なので、その条件に合致しないタイル番号についてはスキップするようにすれば std-6 だけをダウンロードできることになります。

例えば、https://github.com/gsi-cyberjapan/qdltc/blob/gh-pages/qdltc.rb#L100 の直下に

>   (z, x, y) = zxy.split('/')
>   next unless (2..4).include?(z)

というコードを入れていただければ、上記のことが実現できます。

実際には地理院タイル目録はズームレベルが小さい順に並んでいる（← http://www.gsi.go.jp/common/000106650.pdf の3.3）ため、ズームレベルが5になった時点でqdltcを終了してしまうという処理を入れていただくと、プログラムの終了はより早くなると思います。

お試しいただければ幸いです。

地理院タイル目録は、{t} ごとに作成しているため、ダウンロードが必要な地理院タイル目録のURLは、 http://cyberjapandata.gsi.go.jp/xyz/std/mokuroku.csv.gz となります。

いただいた質問は gsimaps というよりは qdltc についての質問となっておりますので、qdltc についての知見を多くの方にお伝えする観点から、追加の質問がありました場合には、https://github.com/gsi-cyberjapan/qdltc/issues のほうにお寄せ頂けますと、多くの方のお役に立つと思います。
