### ISSUE TITLE
layers.txt の id プロパティに / (スラッシュ) が使用されている

### ISSUE THREAD

**Issue by frogcat** [gsi-cyberjapan/gsimaps#78]
layers.txt の id プロパティに / (スラッシュ) が使用されているものがあります。
こちらは意図的なものでしょうか？

https://github.com/gsi-cyberjapan/layers-dot-txt-spec/blob/master/specifications.md とココタイル仕様を読む限りでは、id にカンマを使うのは NG とは思うのですが、スラッシュ含めて使用可能文字については規定がありません。いままでの印象としては、半角英数字とピリオド、マイナス、アンダースコアで構成されていると考えていました。

layers.txt を展開してローカルファイルキャッシュを作ったり、URL の一部に id を含むような使用方法を考えているのですが、スラッシュがある場合にはディレクトリを作ったり別の文字に置換するなどの対応が必要になるので、方針を確認させていただきたく。

**Comment by johofukyu** [comment]
layers3.txtにおいて一部のidに / (スラッシュ)を使用していた点ですが、
これは意図したものではないため、先ほど訂正いたしました。
今後も使用する予定はございません。

この度はご指摘ありがとうございました。
