### ISSUE TITLE
CORS 設定がされていない GeoJSON タイルがある

### ISSUE THREAD

**Issue by frogcat** [gsi-cyberjapan/gsimaps#79]
特定の GeoJSON レイヤー（熊本地震の震央）を選択しても表示されないケースがありました。http://maps.gsi.go.jp/ でも同様の事象がおきています。

http://gsi-cyberjapan.github.io/gsimaps/#10/32.875551/130.928192/&base=std&ls=std%7C20160414kumamoto_epicenter&disp=11&lcd=20160414kumamoto_handoku1&vs=c1j0l0u0f0

ブラウザのエラーメッセージを確認したところ以下のようなメッセージが出力されており、GeoJSON 配信サーバでの CORS ヘッダの付与に問題があるように見受けられます。

![image](https://cloud.githubusercontent.com/assets/12029629/14631837/5541b93a-0650-11e6-82a2-5dd9f5e30f3c.png)

> XMLHttpRequest cannot load http://cyberjapandata.gsi.go.jp/xyz/20160414kumamoto_epicenter/2/3/1.geojson. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://gsi-cyberjapan.github.io' is therefore not allowed access.

全数を確認したわけではないですが、「震央」以外の GeoJSON ファイルは CORS ヘッダが付与されており、表示に問題はないようです。また、時間をおいてアクセスすると「震央」にも CORS ヘッダが付与されているケースもあるようです。（CDN の接続先サーバによって設定が違う？）

ネットワーク環境によっては問題が再現しないかもしれませんし、CDNやキャッシュサーバの設定反映に時間がかかる、といった類の問題かもしれませんが、情報共有のために投稿させていただきました。

**Comment by johofukyu** [comment]
情報提供ありがとうございます。CORS設定について、現状、地理院地図サーバは
Request Headers に Origin が設定されていると
Response Header に access-control-allow-origin を付与し、
そうでないと access-control-allow-originが付与されません。
access-control-allow-originが付与されていないデータをブラウザがキャッシュしていると
ご報告いただいた現象が起きます。
現状、お手数をおかけいたしますが、ブラウザキャッシュクリアをお試しいただければと思います。

**Comment by frogcat** [comment]
ご回答ありがとうございます。

キャッシュの影響を除外するためにコマンドラインの curl でレスポンスヘッダを出力した結果がこちらになります。

![image](https://cloud.githubusercontent.com/assets/12029629/14635014/8f00e68c-065f-11e6-9561-fc3e02c7cc84.png)

上は Origin に http://maps.gsi.go.jp を指定したリクエストに対して、意図したとおりのCORSヘッダの付与されたレスポンスが得られています。

下は Origin に http://gsi-cyberjapan.github.io を指定しているのですが、こちらではCORSヘッダが付与されていませんでした。

この結果を見る限りはキャッシュサーバまわりで「access-control-allow-origin が付与されていないデータ」がキャッシュされている？ような挙動ではないかと思います。

**Comment by johofukyu** [comment]
情報ありがとうございます。調査いたします。

**Comment by johofukyu** [comment]
HEADリクエストに対してもaccess-control-allow-originを返すように設定しました。curl -I -H "Origin: ・・・　のコマンドでも、access-control-allow-originが付与されるようになりました。
ただ、ブラウザからのリクエストについては、以前のコメントしたとおりの現象がおきますので、現状、現象が起きる場合はブラウザキャッシュをお試しください。

**Comment by frogcat** [comment]
調査対応ありがとうございます。

ブラウザについては、Chrome シークレットモードにて geojson を直接表示したのちに、地図上に当該 geojson を表示することで、問題の再現が確認できました。このパターンが問題になるのは開発者くらいですので、特に対策等は不要と思います（せいぜい、なにかあったときにこの Issue に誘導する程度）。

サーバサイドでの HEAD 対応につきましては、3つ上のポストのキャプチャで見る限り、以前も HEAD に対して access-control-allow-origin が付与されているなど、腑に落ちない部分もあるのですが、本件クローズとさせていただければと思います。
