### ISSUE TITLE
UTF-8 Unicode (with BOM) でエンコードされた GeoJSON がある

### ISSUE THREAD

**Issue by frogcat** [gsi-cyberjapan/gsimaps#80]
layers4.txt から参照される 2/3/1 形式の GeoJSON ファイルについて、76ファイル中下記の4ファイルが UTF-8 Unicode (with BOM) でエンコードされていました。これらのファイルをバイナリエディタ等で確認するとファイルの先頭に 0xEF 0xBB 0xBF (zero-width non-breaking space) が挿入されています。
- http://cyberjapandata.gsi.go.jp/xyz/1509typhoon18_shinsui_joso_150914/2/3/1.geojson
- http://cyberjapandata.gsi.go.jp/xyz/20150714_kasairyuresult_kuchinoerabu/2/3/1.geojson
- http://cyberjapandata.gsi.go.jp/xyz/20150911_dourotsuukou_kuchinoerabu/2/3/1.geojson
- http://cyberjapandata.gsi.go.jp/xyz/20150911_kasairyuresult_kuchinoerabu/2/3/1.geojson

BOM ありの JSON はブラウザの JSON Parser では多分問題なくパースできるのですが、寛容でない JSON Parser （たとえば node.js のそれ） ではパースエラーの原因になるので、先頭の BOM を削除してからパースするような対策を各開発者が講じる必要があります。

JSON Parser が寛容になるべき／個々のアプリが対応すべき／JSON の作成者が気をつけるべき、といった議論はたとえばこのあたり https://github.com/npm/npm/issues/3358 でも行われていて、何が正解というわけでもない状況なのですが、 @gsi-cyberjapan として BOM の有無のポリシーを明確にしていただけるとデバッグやレポートはやりやすくなるのではないかと思った次第です。

特に現状困っている、というわけではないのですが同じ問題に遭遇する人のための情報共有も兼ねてポストしました。優先順位の低い要望とお考えください。

**Comment by johofukyu** [comment]
ご指摘いただいた4つのGeoJSONファイルのエンコードがUTF-8 (with BOM)でエンコードされていた件ですが、これは意図したものではないため、先ほどUTF-8（without BOM, UTF-8N）のものに差し替えました。
また、@gsi-cyberjapanとしてはBOM無しのUTF-8Nを使用する方針です。

ご指摘ありがとうございました。
今後ともよろしくお願いいたします。

**Comment by frogcat** [comment]
ご確認ありがとうございます。方針理解しました。
なお、差し替えられたファイルについて、node.js のパーサーでパースしたところエラーなく処理できることを確認できました。
