### ISSUE TITLE
画像タイルに CORS を付与してほしい

### ISSUE THREAD

**Issue by frogcat** [gsi-cyberjapan/gsimaps#88]
Web ブラウザ上で任意の画像タイルを取得し、canvas 上で画像の貼り付け、色に応じたエフェクトなどをかけるアプリケーションの作成を考えています。
このような処理の仕組み自体は以下のページのとおり、すでに整備されています。
<https://developer.mozilla.org/ja/docs/Web/HTML/CORS_enabled_image>

ただ、現在の地理院画像タイルは CORS が設定されておらず、このような用途で使うことができません。GeoJSON や DEM タイルと同様に、画像タイルにも CORS を設定していただけないでしょうか？

**Comment by johofukyu** [comment]
地理院タイルのご利用ありがとうございます。

CORS設定について、地理院地図サーバでは
Request Headers に Origin が設定されているとResponse Header に access-control-allow-origin が付与され、
そうでないと access-control-allow-originが付与されません。
access-control-allow-originが付与されていないデータをブラウザがキャッシュしていると、
ご指摘いただいた問題が発生いたします。

これは、以前 https://github.com/gsi-cyberjapan/gsimaps/issues/79 でご指摘いただいたGeoJSONタイルの挙動と同じです。


現状、お手数をおかけいたしますが、ブラウザのキャッシュクリアや
ブラウザキャッシュを回避するために画像タイルのURL（img.src）にパラメータ（?=○○○）を
つけていただくことなどをお試しいただければと思います。

以上、よろしくお願いいたします。

**Comment by frogcat** [comment]
ご説明ありがとうございます。挙動理解できました。
パラメータ（?=○○○） 付与してみたところ無事取得できました。
