### ISSUE TITLE
apiの提供範囲に北海道の一部範囲が含まれていない事について

### ISSUE THREAD

**Issue by KiyoKando** [gsi-cyberjapan/gsimaps#90]
いつも、素晴らしいサービスをご提供くださり、ありがとうございます。
研究の目的で、地図システム内のリバースジオコーディングを使用させていただいています。

日本全国試してみて、ほぼすべてのケースで動くので、愛用させていただいているのですが、
北海道の白石区については、返り値がありません。
例）返り値：{} 
https://mreversegeocoder.gsi.go.jp/reverse-geocoder/LonLatToAddress?lat=35.698983&lon=141.419263

以下の、id対応表には、白石区が含まれているため、提供範囲内かと思われるので、
不具合ではないかと考え、issueに報告させていただきます。
例）GSI.MUNI_ARRAY["1104"] = '1,北海道,1104,札幌市　白石区';
https://maps.gsi.go.jp/js/muni.js

ご確認、ご対応いただけますと幸いです。
よろしくお願い申し上げます。

**Comment by johofukyu** [comment]
国土地理院の地理院地図担当です。
地理院地図をご利用いただきありがとうございます。

いただいたURLで示されている経緯度 [?lat=35.698983&lon=141.419263]は白石区内ではなく、太平洋上の座標となっております。

ご確認のうえ、不具合が生じている経緯度を教えていただければ幸いです。

なお、白石区役所の経緯度[?lat=43.045513&lon=141.396398]で検索してみたところ以下の値が返ってくることを確認いたしました。
[{"results":{"muniCd":"01104","lv01Nm":"南郷通一丁目南"}}]

どうぞ、よろしくお願いいたします。

**Comment by KiyoKando** [comment]
失礼いたしました。これは、完全に私の勘違いでした。
ご対応いただき、有り難うございました。
