### ISSUE TITLE
新バージョンの地理院地図での出典表示の出し方について

### ISSUE THREAD

**Issue by Miyama-Kirishima** [gsi-cyberjapan/gsimaps#94]
先日バージョンアップして、ますます使いやすくなりました。ありがとうございます。

さて、githubに置かれていた、以前のバージョンの地理院地図では、自動で「地理院タイル」との出典表示が画面右下に入り、layers.txt編集ツールでattribution欄に入力した内容が画面下部に表示されるようになっていました。
新しいバージョンの地理院地図では、初期状態ではこれらの表示がなくなってしまっているようですが、何らか設定を行うことで表示を復活させることができますでしょうか。
御教示いただければ幸いです。

よろしくお願いします。

**Comment by johofukyu** [comment]
ご指摘いただきありがとうございます。
ご指摘の機能に不備があったので、先ほど修正ファイルをアップしました。
ご不便をお掛けして申し訳ありませんでした。
今後ともどうぞよろしくお願いいたします。

**Comment by Miyama-Kirishima** [comment]
さっそく御対応いただきまして、ありがとうございました。
出典表示が表示されることを確認しました。
こちらこそ今度ともどうぞよろしくお願いいたします。

**Comment by Miyama-Kirishima** [comment]
お世話になります。

再度、よく確認したところ、モバイル版では「地理院タイル」の表示が出ないようです。
また、attribution欄に入力した内容もPC版、モバイル版ともに表示されないようです。
（こちらは、gsimaps.jsの14199行目などの /* を取ることで解決することが分かりました。）

御確認いただければ幸いです。

**Comment by johofukyu** [comment]
ご指摘いただきありがとうございます。
モバイル版でもクレジットが表示されるよう修正しました。
また、attribution属性についてですが、こちらの環境では、PC版、モバイル版とも正常に表示されます。
layers*.txtファイルに、「"attribution": "例（aaaa）",」を記述し、地図でそのレイヤを選択すると、画面右下に表示されます。

どうぞよろしくお願いいたします。

**Comment by Miyama-Kirishima** [comment]
今回もさっそく御対応いただきましてありがとうございます。
モバイル版の修正、確認しました。
また、attributionの表示がなされることも確認しました。たいへん失礼いたしました。
御対応、ありがとうございました。
