### ISSUE TITLE
地図の種類検索

### ISSUE THREAD

**Issue by tosseto** [gsi-cyberjapan/gsimaps#95]
以前の地理院地図で，「情報リスト」からキーワード検索できていた機能が，現在の「地図の種類」のインターフェースから使えなくなってしまい，以前に相当する動作の再現できなくなってしまいました．この機能は今後，復活（再機能化）される可能性はあるでしょうか？

**Comment by johofukyu** [comment]
地理院地図をご利用いただきありがとうございます。

今年3月に、情報（レイヤ）名や階層構造を変更することで、情報をより探しやすくしました。
これらの改良により、ご指摘いただいた機能を廃止した次第です。
現時点では、本機能を再実装する予定はございません。
ご了承ください。
以上、よろしくお願いいたします。

**Comment by tosseto** [comment]
早速コメントどうもありがとうございます．
地図に慣れていない利用者からすると，自分が閲覧したいレイヤーがどの大分類に属するか戸惑うことが予想され，でキーワードからも探せると便利ではないかと思いましたが，再実装する予定は無いというご判断については了解しました．
