### ISSUE TITLE
(要望)標高タイルからの等高線生成について

### ISSUE THREAD

**Issue by Miyama-Kirishima** [gsi-cyberjapan/gsimaps#96]
任意の地点の標高は、地理院地図の下部に表示されるようになっていますが、面的に詳細な標高を把握したい場合があります。もちろん10mごとの等高線や色別標高図でもある程度は把握できるのですが、標高タイル（DEM）から任意の間隔で等高線を生成できる機能があれば便利だと思い要望させていただきました。御検討いただければ幸いです。
参考　https://gist.github.com/frogcat/cac7e74534e1c9eb68b95487d0df5465

**Comment by johofukyu** [comment]
ご要望ありがとうございます。
サンプルの方も確認しました。
すばらしい機能だと思います。
ただ、地理院地図（ https://maps.gsi.go.jp/ ）への実装となると、検討・調整すべき点がいくつかあるので、今後の参考意見とさせて頂きます。

もちろん、ご自身のサイトではご自由にその機能を実装し、使っていただいて構いません。

**Comment by Miyama-Kirishima** [comment]
承知いたしました。御検討どうぞよろしくお願いいたします。
（リンク先は私のサイトではありませんが、機能の参考になればと思い添付したものです。念のため。）
